-- 创建家族成员表
CREATE TABLE family_members (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- ID (自动递增)
    name TEXT NOT NULL,                                     -- 姓名
    generation INTEGER,                                     -- 世代
    sibling_order INTEGER,                                  -- 排行
    father_id BIGINT REFERENCES family_members(id),         -- 父亲ID (自关联，用于表达父子关系)
    gender TEXT CHECK (gender IN ('男', '女')),              -- 性别
    official_position TEXT,                                 -- 官职
    is_alive BOOLEAN DEFAULT TRUE,                          -- 是否在世 (TRUE 在世, FALSE 已故)
    spouse TEXT,                                            -- 配偶
    remarks TEXT,                                           -- 备注
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL -- 更新时间
);

-- 为字段添加注释
COMMENT ON TABLE family_members IS '家族成员信息表';
COMMENT ON COLUMN family_members.id IS '唯一标识 ID';
COMMENT ON COLUMN family_members.name IS '姓名';
COMMENT ON COLUMN family_members.generation IS '世代';
COMMENT ON COLUMN family_members.sibling_order IS '排行';
COMMENT ON COLUMN family_members.father_id IS '父亲的 ID (外键关联 ID 字段)';
COMMENT ON COLUMN family_members.gender IS '性别';
COMMENT ON COLUMN family_members.official_position IS '官职';
COMMENT ON COLUMN family_members.is_alive IS '是否在世';
COMMENT ON COLUMN family_members.spouse IS '配偶姓名';
COMMENT ON COLUMN family_members.remarks IS '备注';
COMMENT ON COLUMN family_members.updated_at IS '最后更新时间';

-- 创建索引以优化查询速度
CREATE INDEX idx_family_members_father_id ON family_members(father_id);
CREATE INDEX idx_family_members_name ON family_members(name);